language: python
sudo: false
dist: xenial
cache:
  pip: true
  directories:
    - eggs
    - downloads
python:
  - 2.7
install:
  - virtualenv -p `which python` .
  - bin/pip install -r requirements.txt
  - bin/buildout -Nc travis.cfg buildout:download-cache=downloads code-analysis:return-status-codes=True annotate
  - bin/buildout -Nc travis.cfg buildout:download-cache=downloads code-analysis:return-status-codes=True
script:
  - bin/code-analysis
  - bin/test
after_success:
  - bin/createcoverage
  - pip install coveralls
  - coveralls

notifications:
  email:
    - jk@kleinundpartner.at
